In [19]:
def split(mat):
    m = len(mat)
    n = len(mat[0])
    return mat[:m//2, :n//2], mat[:m//2, n//2:], mat[m//2:, :n//2], mat[m//2:, n//2:]

In [58]:
def strassen1(mat_1, mat_2):

    if(len(mat_1) == 1):
        return mat_1 * mat_2
    a11, a12, a21, a22 = split(mat_1)
    b11, b12, b21, b22 = split(mat_2)
    p = strassen1(a11 + a22, b11 + b22)
    q = strassen1(a21 + a22, b11)
    r = strassen1(a11, b12 - b22)
    s = strassen1(a22, b21 - b11)
    t = strassen1(a11 + a12, b22)
    u = strassen1(a21 - a11, b11 + b12)
    v = strassen1(a12 - a22, a21 + b22)
    
    c11 = p + q - t + v
    c12 = r + t
    c21 = q + s
    c22 = p + r - q - u
    
    return np.vstack((np.hstack((c11, c12)), np.hstack((c21, c22))))

In [59]:
import numpy as np

In [60]:
#do n^3

# Version 3.6

import numpy as np

def split(matrix):
	"""
	Splits a given matrix into quarters.
	Input: nxn matrix
	Output: tuple containing 4 n/2 x n/2 matrices corresponding to a, b, c, d
	"""
	row, col = len(matrix), len(matrix[0])
	row2, col2 = row//2, col//2
	return matrix[:row2, :col2], matrix[:row2, col2:], matrix[row2:, :col2], matrix[row2:, col2:]

def strassen2(x, y):
	"""
	Computes matrix product by divide and conquer approach, recursively.
	Input: nxn matrices x and y
	Output: nxn matrix, product of x and y
	"""

	# Base case when size of matrices is 1x1
	if len(x) == 1:
		return x * y

	# Splitting the matrices into quadrants. This will be done recursively
	# until the base case is reached.
	a11, a12, a21, a22 = split(x)
	b11, b12, b21, b22 = split(y)

	# Computing the 7 products, recursively (p1, p2...p7)
	p = strassen2(a11, b12 - b22)
	q = strassen2(a11 + a12, b22)	
	r = strassen2(a21 + a22, b11)	
	s = strassen2(a22, b21 - b11)	
	t = strassen2(a11 + a22, b11 + b22)	
	u = strassen2(a12 - a22, b21 + b22)
	v = strassen2(a11 - a21, b11 + b12)

	# Computing the values of the 4 quadrants of the final matrix c
	c11 = t + s - q + u
	c12 = p + q		
	c21 = r + s		
	c22 = p + t - r - v

	# Combining the 4 quadrants into a single matrix by stacking horizontally and vertically.
	c = np.vstack((np.hstack((c11, c12)), np.hstack((c21, c22))))

	return c


In [61]:
mat_1 =np.array([[1,1,1,1],[2,2,2,2],[3,3,3,3],[4,4,4,4]])
mat_2 = np.array([[2,2,2,2],[3,3,3,3],[4,4,4,4],[5,5,5,5]])
print(strassen1(mat_1, mat_2))

[[60 36 32 14]
 [56 24 28  4]
 [70 42 28  2]
 [56 32 16 -8]]
